name: kumbo
 
on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'masukin CRD codenya'
        required: true
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Initializing Setup
      run: cmd /c setup1.bat
    - name: config2
      run: cmd /c setup2.bat
    - name: downloads
      run: ./download.ps1
    - name: id conect
      run: cmd /c show.bat
    - name: pasword 
      run: cmd /c glow.bat
    - name: Time Counter
      run: Start-Sleep -Seconds 18000
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
